### ISSUE TITLE
config.js documentation example request

### ISSUE THREAD

**Issue by cl0udb0y** [mathewmeconry/MMM-HomeAssistant-Touch#1]
Hi - great initiative, can you help with some more details on a config please?
e.g. if I were adding this module inside an existing config I would be expecting something like adding the module name and location at min to the provided example. How can you also define each entity? Is this pulled directly from HA? e.g. using friendly name? Can the buttons be overridden?, an simple example of a light switch would be great. Also is there a debug option? The the example below MM starts fine but I don't see the module load. Thanks!

```
 {
    module: "MMM-Homeassistant-touch",
    position: "top_center",
    host: "http://IPADDRESS",
    port: 8123,
    token: "MYTOKEN",
    ignoreCert: false,
    entities: ["ENTITY_ID"],
  },
```

**Comment by mathewmeconry** [comment]
Hi @cl0udb0y 

> How can you also define each entity?

you can add the entities you want into the array `entities`. An example from my integration with a light switch: 
```
{
                        module: "MMM-HomeAssistant-Touch",
                        position: "lower_third",
                        config: {
                                host: "http://127.0.0.1",
                                token: "REDACTED",
                                entities: [
                                        "switch.shelly_shsw_1_aaaaa",
                               ]
                        }
                }

```

> Is this pulled directly from HA?

The module pulls the type and the name from HA and displays it.
There is no way to define a friendly name for an entity in the module, because it pulls the name from HA.

> Can the buttons be overridden?

What do you wanna override?

**Comment by cl0udb0y** [comment]
Hi thanks for the swift response, I'm not having any luck with this. MM loads, no errors but I can't see any evidence the module is being loaded in MM or connection in HASS logs. Anyway to debug the module?

I note your examples have HAAS as local host, HASS in on the same network and on default port 8123 (not metioned above). Does

`port: 8123, ` still stand?

Re the override, I was wondering if the buttons can be graphical icons e.g from mdi?

**Comment by mathewmeconry** [comment]
Hi
you can define the host property like this:
`http(s)://hostname-or-ip`

for example a SSL connection to the non default port with a domain name:
```javascript
{
  config: {
    host: "https://homeassistant.example.com",
    port: 8080
  }
}
```

or another ip on the network with the default port (your case):
```javascript
{
  config: {
    host: "http://192.168.1.5"
  }
}
```

**Comment by cl0udb0y** [comment]
Thanks, it's as I have it and I have tried ipaddress:8123 and without (ie default) and also with port specified as part of the config. I'm testing with two entities but no items appear. Any debug options I can enable?

**Comment by mathewmeconry** [comment]
not really, the service is already really verbose.
the main logs are in the backend, because it handels the connections.
can you send me your config to scherer.mat[at]gmail.com or post it here if you don't mind to publish it publicly

**Comment by cl0udb0y** [comment]
Hi - no probs. Here it is
```
/* Magic Mirror Config Sample
 *
 * By Michael Teeuw http://michaelteeuw.nl
 * MIT Licensed.
 *
 * For more information how you can configurate this file
 * See https://github.com/MichMich/MagicMirror#configuration
 *
 */

var config = {
  address: "", // Address to listen on, can be:
                        // - "localhost", "127.0.0.1", "::1" to listen on loopback interface
                        // - another specific IPv4/6 to listen on a specific interface
                        // - "", "0.0.0.0", "::" to listen on any interface
                        // Default, when address config is left out, is "localhost"
  port: 8080,
  ipWhitelist: [], // Set [] to allow all IP addresses
                                                         // or add a specific IPv4 of 192.168.1.5 :
                                                         // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.1.5"],
                                                         // or IPv4 range of 192.168.3.0 --> 192.168.3.15 use CIDR format :
                                                         // ["127.0.0.1", "::ffff:127.0.0.1", "::1", "::ffff:192.168.3.0/28"],

  language: "en",
  timeFormat: 24,
  units: "metric",

  modules: [
  {
  module: "alert",
  classes: 'default everyone',
  },
  {
  module: "updatenotification",
  classes: 'default everyone',
  position: "top_bar"
  },
  {
  module: "clock",
  classes: 'default everyone',
  position: "top_center"
  },
  {
  module: "MMM-Touch",
  position: "top_center",
  },
  {
    module: "MMM-Homeassistant-touch",
    position: "bottom_bar",
    config: {
            host: "http://REDACTED:8123",
            token: "REDACTED",
            ignoreCert: false,
            entities: [
	              "switch.8chrelay_1",
	              "switch.8chrelay_2"
	              ]
	}
  },
  {
  module: "newsfeed",
  classes: 'default everyone',
  position: "bottom_bar",
  config: {
  feeds: [
                {
                 title: "BBC",
                 url: "http://feeds.bbci.co.uk/news/rss.xml",
                },
                {
                 title: "BBC World",
                 url: "http://feeds.bbci.co.uk/news/world/asia/rss.xml",
                },

         ],
  showSourceTitle: true,
  showPublishDate: true,
  ignoreOlderThan:  172800000,
  showDescription: true,
  wrapDescription: false
         }
},

{
    module: "MMM-RTSPStream",
    position: "middle_center",
    config: {
        autoStart: true,
        rotateStreams: false,
        rotateStreamTimeout: 20,
        moduleWidth: 640,
        moduleHeight: 360,
        localPlayer: 'omxplayer',
        remotePlayer: 'false',
        showSnapWhenPaused: false,
        remoteSnaps: false,
	shutdownDelay: 0,
        stream1: {
            name: 'Drive',
            url: 'rtsp://REDACTED/Streaming/Channels/2',
            protocol: 'tcp',
            width: 640,
            height:360,
            timeout: 30,
            },
         stream2: {
            name: 'Backdoor',
            url: 'rtsp://REDACTED/Streaming/Channels/2',
            protocol: 'tcp',
            width: 640,
            height: 360,
            timeout: 30,
            },
	}
},
{
    module: 'MMM-MQTT',
    position: 'top_left',
    classes: 'default everyone',
    header: 'Elecricity',
    config: {
        mqttServers: [
            {
                address: 'REDACTED',  // Server address or IP address
                port: '1883',          // Port number if other than default
                user: 'emonpi',          // Leave out for no user
                password: 'REDACTED',  // Leave out for no password
                subscriptions: [
                        {
                        topic: 'emon/emonTx_1/power1', // Topic to look for
                        label: 'Power', // Displayed in front of value
                        suffix: 'kW',        // Displayed after the value
			divide: 1000,
                        decimals: 2
			},
			{
                        topic: 'emon/emonTx_1/vrms', // Topic to look for
                        label: 'Voltage', // Displayed in front of value
                        suffix: 'V',        // Displayed after the value
                        decimals: 0
                        },
			{
                        topic: 'emon/emonTx_1/power1_kWhd', // Topic to look for
                        label: 'Used today', // Displayed in front of value
                        suffix: 'kWh',        // Displayed after the value
                        decimals: 2
                        },
			{
                        topic: 'emon/emonTx_1/power1_cost_pd', // Topic to look for
                        label: 'Day Cost £', // Displayed in front of value
                        //suffix: '£',        // Displayed after the value
                        decimals: 2
                        },
			{
                        topic: 'emon/emonTx_1/power1_cost_pn', // Topic to look for
                        label: 'Night Cost £', // Displayed in front of value
                        //suffix: '£',        // Displayed after the value
                        decimals: 2
                        },
			{
                        topic: 'emon/emonTx_1/power1_cost_day_total', // Topic to look for
                        label: 'Total Cost today £', // Displayed in front of value
                        //suffix: '£',        // Displayed after the value
                        decimals: 2
                        }
			]
            }
        ],
    }
},		

{
    module: 'MMM-MQTT',
    position: 'top_left',
    classes: 'default everyone',
    header: 'Water',
    config: {
        mqttServers: [
            {
                address: 'REDACTED',  // Server address or IP address
                port: '1883',          // Port number if other than default
                // user: 'user',          // Leave out for no user
                // password: 'password',  // Leave out for no password
                subscriptions: [
			{
                        topic: 'homeassistant/sensor/60019449A0B1/out', // Topic to look for
                        label: 'Mains Flowrate', // Displayed in front of value
                        suffix: 'Lt/min',        // Displayed after the value
                        decimals: 1,
			jsonpointer: '/currentFlowRate'
                        },
			{
                        topic: 'homeassistant/sensor/60019449A0B1/out', // Topic to look for
                        label: 'House Water Used', // Displayed in front of value
                        suffix: 'm³',        // Displayed after the value
                        divide: 1000,
			decimals: 2,
			jsonpointer: '/TotalVolume'
                        },
                        {
                        topic: 'homeassistant/sensor/A4CF12F4E0DA/out', // Topic to look for
                        label: 'Well Flowrate', // Displayed in front of value
                        suffix: 'Lt/min',        // Displayed after the value
                        decimals: 1,
                        jsonpointer: '/currentFlowRate'
                        },
                        {
                        topic: 'homeassistant/sensor/A4CF12F4E0DA/out', // Topic to look for
                        label: 'Well Water Used', // Displayed in front of value
                        suffix: 'm³',        // Displayed after the value
                        decimals: 2,
			divide: 1000,
                        jsonpointer: '/TotalVolume'
                        }

                ]
            }
        ],
    }
},

/*{
	module: 'MMM-homeassistant-sensors',
	position: 'top_left',
	config: {
		host: "REDACTED",
		port: "8123",
		https: false,
		token: "REDACTED",
                prettyName: false,
		stripName: false,
		debuglogging: true,
		values: [
			{
				sensor: "sensor.emoncms_use_kwh",
			},
		]
	}
},
*/

{
  module: "MMM-DarkSkyForecast",
  header: "Surlingham",
  classes: 'default everyone',
  position: "top_right",
  classes: "default everyone",
  disabled: false,
  config: {
    apikey: "REDACTED",
    latitude: "REDACTED",
    longitude: "REDACTED",
    iconset: "4c",
    concise: true,
    colored: true,
    units: 'uk2',
    hourlyForecastInterval: 4,
    maxHourliesToShow: 2,
    showDailyForecast: true,
    maxDailiesToShow: 3,
    useAnimatedIcons: true,
    forecastLayout: "table"
  }
 },
 ]
};

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== "undefined") {module.exports = config;}
```

**Comment by mathewmeconry** [comment]
Also
change this line `host: "http://REDACTED:8123",` to `host: "http://REDACTED",`
The port (if you don't use the default one) can be changed with the `port` property as shown in example in the comment above.

**Comment by cl0udb0y** [comment]
Thanks / I have tried those combinations. No luck. You says it's 'verbose' I don't see that, even if I add debug: true to the config. I'm using pm2 to manage MM so pm2 logs to see the output and this module is not reporting much at all.

0|mm  | Starting MagicMirror: v2.16.0
0|mm  | [11.09.2021 13:32.13.891] [LOG]   
0|mm  | Loading config ...
0|mm  | [11.09.2021 13:32.13.937] [LOG]   Loading module helpers ...
0|mm  | [11.09.2021 13:32.13.950] [LOG]   No helper found for module: alert.
0|mm  | [11.09.2021 13:32.14.778] [LOG]   
0|mm  | Initializing new module helper ...
0|mm  | [11.09.2021 13:32.14.784] [LOG]   
0|mm  | Module helper loaded: updatenotification
0|mm  | [11.09.2021 13:32.14.790] [LOG]   
0|mm  | No helper found for module: clock.
0|mm  | [11.09.2021 13:32.14.807] [LOG]   
0|mm  | Initializing new module helper ...
0|mm  | [11.09.2021 13:32.14.811] [LOG]   Module helper loaded: MMM-Touch
0|mm  | [11.09.2021 13:32.14.818] [LOG]   
0|mm  | No helper found for module: MMM-Homeassistant-touch.
0|mm  | [11.09.2021 13:32.15.007] [LOG]   
0|mm  | Initializing new module helper ...
0|mm  | [11.09.2021 13:32.15.011] [LOG]   Module helper loaded: newsfeed
0|mm  | [11.09.2021 13:32.18.687] [LOG]   
0|mm  | Initializing new module helper ...
0|mm  | [11.09.2021 13:32.18.693] [LOG]   
0|mm  | Module helper loaded: MMM-RTSPStream
0|mm  | [11.09.2021 13:32.19.206] [LOG]   
0|mm  | Initializing new module helper ...
0|mm  | [11.09.2021 13:32.19.209] [LOG]   Module helper loaded: MMM-MQTT
0|mm  | [11.09.2021 13:32.20.766] [LOG]   
0|mm  | Initializing new module helper ...
0|mm  | [11.09.2021 13:32.20.769] [LOG]   
0|mm  | Module helper loaded: MMM-DarkSkyForecast
0|mm  | [11.09.2021 13:32.20.773] [LOG]   All module helpers loaded.
0|mm  | [11.09.2021 13:32.21.185] [LOG]   
0|mm  | Starting server on port 8080 ... 
0|mm  | [11.09.2021 13:32.21.224] [WARN]  
0|mm  | You're using a full whitelist configuration to allow for all IPs
0|mm  | [11.09.2021 13:32.21.265] [LOG]   
0|mm  | Server started ...
0|mm  | [11.09.2021 13:32.21.271] [LOG]   Connecting socket for: updatenotification
0|mm  | [11.09.2021 13:32.21.279] [LOG]   
0|mm  | Connecting socket for: MMM-Touch
0|mm  | [11.09.2021 13:32.21.285] [LOG]   Starting module helper: MMM-Touch
0|mm  | [11.09.2021 13:32.21.290] [LOG]   Connecting socket for: newsfeed
0|mm  | [11.09.2021 13:32.21.296] [LOG]   
0|mm  | Starting node helper for: newsfeed
0|mm  | [11.09.2021 13:32.21.303] [LOG]   Connecting socket for: MMM-RTSPStream
0|mm  | [11.09.2021 13:32.21.310] [LOG]   PM2: Stopping all OMXPlayer Streams...
0|mm  | [11.09.2021 13:32.21.323] [LOG]   Connecting socket for: MMM-MQTT
0|mm  | [11.09.2021 13:32.21.328] [LOG]   MMM-MQTT: Starting node helper
0|mm  | [11.09.2021 13:32.21.335] [LOG]   Connecting socket for: MMM-DarkSkyForecast
0|mm  | [11.09.2021 13:32.21.341] [LOG]   
0|mm  | ====================== Starting node_helper for module [MMM-DarkSkyForecast]
0|mm  | [11.09.2021 13:32.21.345] [LOG]   Sockets connected & modules started ...
0|mm  | [11.09.2021 13:32.22.422] [LOG]   
0|mm  | Launching application.

it looks like it's just not loading... ???

**Comment by mathewmeconry** [comment]
As I can see read from this line `0|mm | No helper found for module: MMM-Homeassistant-touch.` is that the module isn't loading properly...
Is there a file called `node_helper.js` in the MMM-HomeAssistant-Touch folder?

**Comment by cl0udb0y** [comment]
Hi - yep it's present and up to date...
pi@magicmirror2:~/MagicMirror/modules/MMM-HomeAssistant-Touch $ ls
helpers  MMM-HomeAssistant-Touch.css  MMM-HomeAssistant-Touch.js  node_helper.js  node_modules  package.json  package-lock.json  Readme.md  screenshots  UIClasses

pi@magicmirror2:~/MagicMirror/modules/MMM-HomeAssistant-Touch $ git pull
Already up to date.

**Comment by mathewmeconry** [comment]
ahh grrr I finally found it
you have a typo in the module name

it should be MMM-Home**A**ssistant-Touch and not MMM-Homeassistant-Touch

**Comment by id-ic** [comment]
Not to add anything distracting to this but I seem to be having about the same issue as cl0udb0y.  In MM i get my buttons outline displayed but it just says "loading...".

**Comment by mathewmeconry** [comment]
Hi @id-ic 
cl0udb0y has a typo that is why the module is not loading.
Please open a new issue with your config and the logs you see.

**Comment by mathewmeconry** [comment]
@id-ic closing the issue now because of a lack of response. Don't mind to reopen the issue if the problem still exists

**Comment by jgillamtmforum** [comment]
yikes, thanks for that spot :-( - yep confirmed working.
