### ISSUE TITLE
Touch doesn't work

### ISSUE THREAD

**Issue by fikkiovarrikkio** [mathewmeconry/MMM-HomeAssistant-Touch#4]
Hi.
I install this module on my mirror.
Apparently all work good, only the touch doesn't work.

I explane:

this is my code 

```
                        module: "MMM-HomeAssistant-Touch",
                        position: "lower_third",
                        config: {
                                host: "http://192.168.0.106",
                                port: 8123,
                                token: "myToken"
                                ignoreCert: false,
                                entities: [
                                        "switch.1000cb1cec_2",
                                        "switch.1000cb0cf2_1",
                               ],
                        }
                },

```

And this is what i see on the mirror

![2022-03-21-235045_1920x1080_scrot](https://user-images.githubusercontent.com/64835395/159376338-3f8e94c9-3302-4c80-b0a5-1b36f9cbcf2f.png)

 and on terminal

![Immagine 2022-03-21 235254](https://user-images.githubusercontent.com/64835395/159376342-2dd377c7-8468-47df-929f-bbb957cdf633.jpg)

Now, if i touch one of the two light on the mirror, nothing happenes and i see this on the terminal

![Immagine 2022-03-21 235631](https://user-images.githubusercontent.com/64835395/159376518-b6f75ca5-64f8-4607-a8f4-68a23796f9dd.jpg)

instead if I use my ewelink App or Home Assistant, i se the switch on the mirror and all work good

mirror side

![2022-03-21-235920_1920x1080_scrot](https://user-images.githubusercontent.com/64835395/159376879-53a2efe6-6de1-48a5-a4fc-b869071cae1c.png)

Terminal side

![Immagine 2022-03-21 235945](https://user-images.githubusercontent.com/64835395/159376903-c0bb2b7f-a37a-4b44-b055-82bdc98acf8c.jpg)

So, module listen what happened by Home Assistant, and when I touch the switch on the mirror something happen, but the signal don't arrive to destination.

Have been someone same problem and can help me?

Thank you so much

**Comment by mathewmeconry** [comment]
Hey
this is odd.
Does the touch work in general? 
and can you post me the logs of the module after you have touched the button? I ask this because the last 2 log images are the same

**Comment by fikkiovarrikkio** [comment]
Hi, thank you for your support.

Yes, the touch work in general.

This terminal image rapresent what happen when I touch the mirror

https://user-images.githubusercontent.com/64835395/159376518-b6f75ca5-64f8-4607-a8f4-68a23796f9dd.jpg

so raspy read the touch and give me a feedback, but my light doesn't switch.

If i work on ewelink App or Home Assistant, i see the switch on the mirror.

I don't know if you need some other information

**Comment by mathewmeconry** [comment]
If this screenshot is after you pressed the button on the mirror everything looks ok to me. 
the mirror triggers the toggle in home assistant according to the logs

**Comment by fikkiovarrikkio** [comment]
of course this is the bag.

My mirror read my home assistant account and give exact name to entity;
If i switch light whit physical button, ewelink app or home assistant app, mirror rides well the state;
If i switch the light on the mirror, terminal ride the action;

But the finaly action death, as if the terminal doesn't send the information to home assistant!

I thought someone maybe had same problem, but apparently this is the first time this happened

**Comment by mathewmeconry** [comment]
yep, the first time I hear this but I also don't know how many people, besides me, are using this.
Do you see any change in the home assistant logs (the UI and in the terminal) when you push the button on the mirror?

**Comment by mathewmeconry** [comment]
@fikkiovarrikkio were you able to resolve it?

**Comment by fikkiovarrikkio** [comment]
Sorry for delay.
I doesn't solve it, but in this moment my work doesn't allow me to study it.
I will try again soon and I answer you.

Thank you for your availability

**Comment by mathewmeconry** [comment]
Hi @fikkiovarrikkio 
In favor of house keeping I close this issue. Feel free to reopen it when you have time
