### ISSUE TITLE
Not getting it to work

### ISSUE THREAD

**Issue by WilliamFredriksson1** [mathewmeconry/MMM-HomeAssistant-Touch#6]
I can not get it to work, I beleve the issue is that I do not have a API Token, nor do I know how I get one.

But this is how my configuration looks like 

 {		    
		    host: "http://127.0.0.1",
		    port: 8123,
		    token: "Valid",
		    ignoreCert: false,
		    entities: [
			"scene.vardagsrum_slack"
		      ],
		  },

**Comment by mathewmeconry** [comment]
Hi
You need a so called "Long Lived Access Token" and it can be obtained via the Homeassistant Webinterface in the account profile section
https://www.home-assistant.io/docs/authentication/#your-account-profile
