### ISSUE TITLE
Cant run automations and they get wierd names,

### ISSUE THREAD

**Issue by WilliamFredriksson1** [mathewmeconry/MMM-HomeAssistant-Touch#7]
Hello, I can get the scenes and automations to show on the MM. 
But nothing happens when I click them, I am wondering how I can make it so that if I click on the box it runs the automation?

And another question, as you can see from the picture the boxes are called stuff like "Dagljus (Unsupported) 2024-02 etc" or "Släck Allt (Unsupported) etc"

Here is my config:
 {
		    module: "MMM-HomeAssistant-Touch",
		    position: "middle_center",
		    config: {		    
			  host: "http://MY-IP",
			  port: 8123,
			  token: "[REDACTED]",
			  ignoreCert: false,
			  entities: [
			      "scene.dagsljus",
			      "scene.slack_allt",
			      "scene.morgonljus",
			      "scene.se_tv",
			      "automation.hall_lampknapp_klickad",
			      "automation.kok_lapmknapp_klickad",
			      "automation.vardagsrum_lapmknapp_klickad"
			  ]
			}
		  },

![bild](https://github.com/mathewmeconry/MMM-HomeAssistant-Touch/assets/154243601/d3f29604-11d3-48e9-8761-1721a707a825)

**Comment by WilliamFredriksson1** [comment]
Also, I dont know if this could change anything. But I have another module called "MMM-Touch" I am not at home right now so I cant try and remove that module and see if it works then. When I get home from work Ill try that and update

**Comment by mathewmeconry** [comment]
Hey @WilliamFredriksson1 

This module doesn't support scenes or automation yet...
If you want to add support for it you would need to create a new class in [UIClasses](https://github.com/mathewmeconry/MMM-HomeAssistant-Touch/tree/master/UIClasses) and add the websocket events in the [nodejs helper](https://github.com/mathewmeconry/MMM-HomeAssistant-Touch/blob/80f96976ee960ccf8535e6034b13eb4c815623ec/node_helper.js#L45) to handle the logic

You are currently seeing the [Unsupported Class](https://github.com/mathewmeconry/MMM-HomeAssistant-Touch/blob/master/UIClasses/Unsupported.js)

Currently, I don't have much time to add it myself but it should be pretty straightforward

**Comment by WilliamFredriksson1** [comment]
Okey, Thanks for the tips :)
